# Generated by Django 5.2.6 on 2025-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
