# Generated by Django 5.2.6 on 2025-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example_slug', unique=True),
            preserve_default=False,
        ),
    ]
